INPUT_SIZE = 467
HIDDEN_SIZE = 500
OUTPUT_SIZE = 2
LEARNING_RATE = 0.001
BATCH_SIZE = 32
EPOCHS = 100
TEST_SPLIT = 0.2
VAL_SPLIT = 0.25


# configs do dataset
DATASET_PATH =  None #DEIXE NONE SE FOR RODAR O DATASET PADRÃO DO CÓDIGO

